[package]
name = "sitemap2urllist"
version = "0.1.0"
edition = "2021"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
description = "Read a sitemap and output a list of URLs."
repository = "https://github.com/lukehsiao/sitemap2urllist"
homepage = "https://github.com/lukehsiao/sitemap2urllist"
license = "BlueOak-1.0.0"
keywords = ["sitemap", "urllist"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.21", features = ["derive", "wrap_help", "cargo"] }
clap-verbosity-flag = "3.0.1"
csv = "1.3.1"
dashmap = "6.1.0"
humantime = "2.1.0"
jiff = { version = "0.1.15", features = ["serde"] }
log = "0.4.22"
miette = { version = "7.4.0", features = ["fancy"] }
reqwest = { version = "0.12.9", features = ["gzip", "brotli", "zstd", "deflate"] }
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["full"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
url = { version = "2.5.4", features = ["serde"] }
yansi = { version = "1.0.1", features = ["detect-tty", "detect-env"] }
