[package]
name = "sitemap2urllist"
version = "0.1.4"
edition = "2024"
authors = ["Luke Hsiao <luke@hsiao.dev>"]
description = "Read a sitemap and output a list of URLs."
repository = "https://github.com/lukehsiao/sitemap2urllist"
homepage = "https://github.com/lukehsiao/sitemap2urllist"
license = "BlueOak-1.0.0"
keywords = ["sitemap", "urllist"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.32", features = ["derive", "wrap_help", "cargo"] }
clap-verbosity-flag = "3.0.2"
csv = "1.3.1"
dashmap = "6.1.0"
humantime = "2.2.0"
jiff = { version = "0.2.4", features = ["serde"] }
log = "0.4.26"
quick-xml = { version = "0.37.5", features = ["serialize"] }
reqwest = { version = "0.12.15", features = ["gzip", "brotli", "zstd", "deflate"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1.41"
tracing-log = "0.2.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
url = { version = "2.5.4", features = ["serde"] }

[dev-dependencies]
pretty_assertions = "1.4.1"
